version: "3.9"

services:
  dash:
    build:
      context: ./dash
      dockerfile: Dockerfile
    container_name: 'dash'
    restart: always
    tty: true
    expose:
      - "8050"
    ports:
      - "8050:8050"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/dash-docker/dash/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/dash:/root/dash/
     